description: |
  Report builds or deployments to Compass based on job type.

parameters:
  environment:
      default: ${CIRCLE_JOB}
      description: For deployments. Indicates the name of target environment. Default is the CircleCI Job Name.
      type: string
  environment_type:
      default: development
      description: Indicates the category of target environment as defined by Atlassian
      enum:
          - production
          - staging
          - testing
          - development
          - unmapped
      type: enum
  state_path:
      default: ./circleci-orb-compass.status
      description: Relative or absolute path to a store build state for orb.
      type: string
  token_name:
      default: CIRCLE_TOKEN
      description: The name of environment variable containing CircleCI API Token. Required for all projects.
      type: string
steps:
  - jq/install:
      when: always
  - run:
      command: |
          echo 'COMPASS_BUILD_STATUS="FAILED"' > <<parameters.state_path>>
      name: COMPASS - Setting Failure Condition
      when: on_fail
  - run:
      command: |
          echo 'COMPASS_BUILD_STATUS="SUCCESSFUL"' > <<parameters.state_path>>
      name: COMPASS- Setting Success Condition
      when: on_success
  - run:
      environment:
          TOKEN_NAME: <<parameters.token_name>>
          STATE_PATH: <<parameters.state_path>>
          ENVIRONMENT_TYPE: <<parameters.environment_type>>
      command: <<include(scripts/notify_deployment.sh)>>
      name: Update status in Atlassian Compass
      when: always