---
description: |
  Report deployments to Compass
usage:
  version: 2.1
  orbs:
    <orb>: <namespace>/<orb>@x.y
  jobs:
    deploy:
      docker:
        - image: 'circleci/node:10'
      steps:
        - run: echo "hello"
orbs:
  workflows:
    deploy:
      jobs:
        - deploy:
          post-steps:
            - compass/notify_deployment
